---
title: "Practical 3"
author: "Richard J. Telford"
date: "May 27, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## GLS

With the built-in `iris` data.

Make a plot to show how `Petal.Length` varies between species.

Find the variance of `Petal.Length` for each species.

Fit an anova using `lm` between `Petal.Length` and species and examine the diagnostic plots.

Fit a `gls` for the same model. Have the coefficients changed?

Fit a `gls` for the same model but allow the variance to be different for each species. 

Use `AIC` to test if this is a better model.


library(ggplot2)
library(tidyverse)
data (iris)

iris <- as_tibble (iris)

##Plot Petal Length by Species
iris %>% group_by (Species) %>% count (Petal.Length) %>% 
ggplot (aes(x=n, y=Petal.Length, fill=Species)) + geom_violin()


##Find variance 
iris %>% group_by(Species) %>% 
summarise (variance = var(Petal.Length))

##ANOVA and Diagnostic plots 
iris.lm <- lm (Petal.Length ~ Species, data = iris)
anova (iris.lm)

##shows four different diagnostic plots
plot (iris.lm)



#Fit an GLS for the same model. Has the coefficient changed?
library (nlme)


fit_gls1 <- gls(Petal.Length ~ Species, data = iris)
anova (fit_gls1)
summary (fit_gls1)

##It will show my coefficient. Then I need to compare with ANOVA: coefficient haven´t changed, because I haven´t added weights.



##Fit GLS with weights 

fit_gls2 <- gls(Petal.Length ~ Species, data = iris, weights = varIdent (form = ~ +1 |Species))
anova (fit_gls2)
summary (fit_gls2)

## Coefficient stays the same, AIC (estimate of fit) decreases, the lower the AIC, the better fit the model, so my model is better explained and better for predictions. 
# NLS

- Import data amount.csv
- Do a non-linear regression
- Interpret the results
- What is the expected value if calcium = 10?
